In [39]:
import numpy as np

N = 7
a = np.hstack((np.arange(0, N//2), np.linspace(N//2, 0, N//2+1)))
b = a
for i in range(1, N):
    b = np.vstack((b, a+a[i]))
print(b)

[[0. 1. 2. 3. 2. 1. 0.]
 [1. 2. 3. 4. 3. 2. 1.]
 [2. 3. 4. 5. 4. 3. 2.]
 [3. 4. 5. 6. 5. 4. 3.]
 [2. 3. 4. 5. 4. 3. 2.]
 [1. 2. 3. 4. 3. 2. 1.]
 [0. 1. 2. 3. 2. 1. 0.]]


In [41]:
[[True, False], [False, False]].asList()

AttributeError: 'list' object has no attribute 'asList'