In [39]:
import numpy as np

N = 7
a = np.hstack((np.arange(0, N//2), np.linspace(N//2, 0, N//2+1)))
b = a
for i in range(1, N):
    b = np.vstack((b, a+a[i]))
print(b)

[[0. 1. 2. 3. 2. 1. 0.]
 [1. 2. 3. 4. 3. 2. 1.]
 [2. 3. 4. 5. 4. 3. 2.]
 [3. 4. 5. 6. 5. 4. 3.]
 [2. 3. 4. 5. 4. 3. 2.]
 [1. 2. 3. 4. 3. 2. 1.]
 [0. 1. 2. 3. 2. 1. 0.]]


In [8]:
16 not in range(1, 17)

False

In [14]:
field = [[1,2],[3,4]]
Wmap = [[1,2],[3,4]]

for p in zip(field, Wmap):
    print(p)

k = [[c + d for c, d in zip(a, b)] for a, b in zip(field, Wmap)]
k = [a for line in k for a in line]
p = lambda i: k[i]
god = max(range(len(k)), key=p)
print(god)

([1, 2], [1, 2])
([3, 4], [3, 4])
3
